title = "Shubham Pai"
baseURL = "https://blah.com"
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
canonifyURLs = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  recent_posts_number = 3

[menus]
[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menus.main]]
    name = 'Resume'
    pageRef = '/resume'
    weight = 20
[[menus.main]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 30

[[params.ananke_socials]]
name = "linkedin"
url = "https://linkedin.com/in/shubhampai"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/ShubhamPai99"

[[params.ananke_socials]]
name = "instagram"
url = "https://instagram.com/shotsbyshubs"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/shubhampai_"